# Generated by Django 5.2.9 on 2025-12-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='S1', max_length=255),
            preserve_default=False,
        ),
    ]
