# Generated by Django 5.2.9 on 2025-12-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('ME', 'Meeting'), ('CA', 'Call'), ('EM', 'Email'), ('OT', 'Other')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
