# Generated by Django 5.2.9 on 2025-12-17 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_activity_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
    ]
