# Generated by Django 5.2.9 on 2025-12-17 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_address_options'),
        ('marketing', '0004_alter_activity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prospect',
            name='email',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='phone',
        ),
        migrations.AddField(
            model_name='prospect',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
            preserve_default=False,
        ),
    ]
