# Generated by Django 5.2.9 on 2025-12-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_remove_prospect_email_remove_prospect_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospect',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
