# Generated by Django 5.2.9 on 2025-12-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='reference',
            field=models.CharField(default='eca80922dfd0', editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
