# Generated by Django 5.2.9 on 2025-12-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_bill_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='reference',
            field=models.CharField(default='d2a093b333c5', editable=False, max_length=12, primary_key=True, serialize=False, unique=True),
        ),
    ]
